# sing-box 快速命令（放入 ~/.config/fish/config.fish 或 source 本文件）
alias sb 'singbox'
alias sb-tui 'singbox-tui'
alias sb-on 'singbox start'
alias sb-off 'singbox stop'
alias sb-restart 'singbox restart'
alias sb-status 'singbox status'
alias sb-switch 'singbox switch'
alias sb-mode 'singbox mode'
alias sb-nodes 'singbox nodes'
alias sb-speed 'singbox speed'
alias sb-udp 'singbox udp'
alias sb-log 'singbox log'
alias sb-rules 'singbox rules'
alias sb-backup 'singbox backup'
alias sb-sub 'singbox subscribe'
alias sb-env 'singbox env'
alias sb-guard 'singbox guard'
alias sb-sec 'singbox sec'
